!classDefinition: #Auto1 category: 'Ejercicios-IS1'!
DenotativeObject subclass: #Auto1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicios-IS1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Auto1 class' category: 'Ejercicios-IS1'!
Auto1 class
	instanceVariableNames: ''!

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:32:02'!
asHtml! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:32:13'!
asJson! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:21:55'!
break! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:22:15'!
openTrunk! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:32:08'!
save! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:21:50'!
speedUp! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:21:44'!
turnOff! !

!Auto1 class methodsFor: 'as yet unclassified' stamp: 'nz 3/27/2021 12:21:30'!
turnOn! !
